Movie_Management/Controllers/ActorController.cs
using Movie_Management.Service.ActorService;
using System;
using System.Web.Mvc;

namespace Movie_Management.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorsService _actors;

        public ActorController(IActorsService actors)
        {
            _actors = actors;
        }

        //[HttpGet]
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [HttpGet]
        public JsonResult GetActors()   
        {
            var result = _actors.GetActors();
            
            if (result != null)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                const string message = "Failed";
                return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult SaveActor(long? ActorId,string ActorName,string ActorSex,DateTime ActorDob,string ActorBio)
        {
            var result = _actors.SaveActor(ActorId, ActorName, ActorSex, ActorDob, ActorBio);

            if (result!=null)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                const string message = "Failed to insert! Please try again";
                return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult DeleteActor(long id)
        {
            var result = _actors.DeleteActor(id);

            var message = result ? "Success" : "Failed to Delete! Please try again";
            return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpGet]
        public JsonResult EditActor(long id)
        {
            var result = _actors.EditActor(id);
            if (result != null)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                const string message = "Failed";
                return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

    }
}

Movie_Management/Controllers/MovieController.cs
using Movie_Management.Service.MovieService;
using System;
using System.IO;
using System.Web.Mvc;

namespace Movie_Management.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;

        public MovieController(IMovieService movie)
        {
            _movieService = movie;
        }

        //[HttpGet]
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //[HttpGet]
        //public ActionResult CreateMovie()
        //{
        //    return View();
        //}

        [HttpPost]
        public JsonResult SaveUploadImage()
        {
            var message = string.Empty;
            var flag = false;
            if (Request.Files == null) return new JsonResult {Data = new {Message = message, Status = false}};
            var file = Request.Files[0];
            if (file == null) return new JsonResult {Data = new {Message = message, Status = false}};
            var fileName = file.FileName;

            try
            {
                file.SaveAs(Path.Combine(Server.MapPath("~/UploadedImages/" + fileName)));
                message = "File uploaded";
                flag = true;
            }
            catch (Exception)
            {
                message = "File upload failed! Please try again";
            }

            return new JsonResult { Data = new { Message = message, Status = flag } };
        }

        [HttpPost]
        public JsonResult SaveMovie(string ShowName,string ShowYearOfRelease,string ShowPlot,string ImagePath,long EntertainmentId,long[] Cast)
        {
            var result =_movieService.SaveMovie(ShowName, ShowYearOfRelease, ShowPlot, ImagePath, EntertainmentId,Cast);

            var message = result ? "Success" : "Failed";
            return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpGet]
        public JsonResult GetAllMovies()
        {
            var result = _movieService.GetAllMovie();
            if(result != null)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                const string message = "Failed";
                return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        //[HttpGet]
        //public ActionResult Edit()
        //{
        //    return View();
        //}

        [HttpGet]
        public JsonResult EditMovie(long id)
        {
            var result = _movieService.EditMovie(id);

            if (result != null)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                const string message = "Failed";
                return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult EditMovieDetails(long showId, string ShowName, string ShowYearOfRelease, string ShowPlot, string ImagePath, long EntertainmentId, long[] Cast)
        {
            var result = _movieService.EditMovieDetails(showId, ShowName, ShowYearOfRelease, ShowPlot, ImagePath, EntertainmentId, Cast);

            var message = result ? "Success" : "Failed";
            return new JsonResult { Data = message, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

Movie_Management/Views/Actor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid" ng-controller="movieController">
    <h2>Actors List</h2>
    <button class="btn btn-success" style="float:right; margin-bottom:15px;" data-toggle="modal" focus-element="autofocus" data-target=".bs-example-modal-lg">
        <i class="fa fa-plus" style="padding-right:5px;"></i>Add Actor
    </button>

    <div class="col-lg-12 col-sm-12 col-xs-12 alert alert-info" ng-show="bool">
        <strong>{{message}}</strong>
    </div>
    <table class="table table-responsive table-bordered">
        <thead>
            <tr>
                <th class="col-lg-2">Actor Name</th>
                <th class="col-lg-2">Actor Gender</th>
                <th class="col-lg-3">Actor DOB</th>
                <th class="col-lg-4">Actor Bio</th>
                <th class="col-ld-1">Action</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="a in Actors | filter:serachText">
                <td>{{a.ActorName}}</td>
                <td>{{a.ActorSex}}</td>
                <td>{{a.ActorDOB | date : "dd-MM-yyyy"}}</td>
                <td>{{a.ActorBio}}</td>
                <td>
                    @*<a><i class="fa fa-pencil" style="margin-right:10px; font-size:large;" ng-click="EditActor(a.ActorId)"></i></a>*@
                    <a><i class="fa fa-trash" style="font-size:large;" ng-click="deleteActorDetail($index,a.ActorId)"></i></a>
                </td>
            </tr>
        </tbody>
    </table>
    <div style="text-align:center;">
        <strong>{{TableRecordMessage}}</strong>
    </div>
</div>


<div class="modal fade bs-example-modal-lg" focus-group focus-group-head="loop" ng-controller="movieController" focus-group-tail="loop" focus-stacktabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Add Actor</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" ng-controller="movieController" novalidate name="f1" ng-submit="saveActor(actorName,gender,dob,bio)">
                    <div class="col-lg-12 col-sm-12 col-xs-12 alert alert-info" ng-show="bool">
                        <strong>{{message}}</strong>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Actor Name</label>
                        <div class="col-sm-6">
                            <input type="text" name="actorName" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="actorName" required autofocus />
                            <span class="error" ng-show="(f1.actorName.$dirty || submitted) && f1.actorName.$error.required">Name is required!</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Gender</label>
                        <div class="col-md-2">
                            Male<input type="radio" name="gender" value="male" ng-model="gender" ng-required="!gender" />
                        </div>
                        <div class="col-md-2">
                            Female<input type="radio" name="gender" value="female" ng-model="gender" ng-required="!gender" />
                        </div>
                        <div class="col-md-2">
                            Others<input type="radio" name="gender" value="others" ng-model="gender" ng-required="!gender" />
                        </div>
                        <span class="error" ng-show="(f1.gender.$dirty || submitted) && f1.gender.$error.required">Gender required!</span>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Date Of Birth</label>
                        <div class="col-sm-6">
                            <input type="date" name="date" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="dob" required autofocus />
                            <span class="error" ng-show="(f1.date.$dirty || submitted) && f1.date.$error.required">Date of Birth is required</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Bio</label>
                        <div class="col-sm-6">
                            <textarea rows="5" name="bio" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="bio" required autofocus></textarea>
                            <span class="error" ng-show="(f1.bio.$dirty || submitted) && f1.bio.$error.required">Enter the bio</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <input type="submit" value="{{submitText}}" class="btn btn-primary">
                    <button type="button" class="btn btn-default" focus-element="autofocus" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bs-edit-modal-lg" id="#EditModal" focus-group focus-group-head="loop" ng-controller="movieController" focus-group-tail="loop" focus-stacktabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Edit Actor</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" ng-controller="movieController" novalidate name="f1" ng-submit="saveActor(actorName,gender,dob,bio)">
                    <div class="col-lg-12 col-sm-12 col-xs-12 alert alert-info" ng-show="bool">
                        <strong>{{message}}</strong>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Actor Name</label>
                        <div class="col-sm-6">
                            <input type="text" name="actorName" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="Edit.ActorName" required autofocus />
                            <span class="error" ng-show="(f1.actorName.$dirty || submitted) && f1.actorName.$error.required">Name is required!</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Gender</label>
                        <div class="col-md-2">
                            Male<input type="radio" name="gender" value="male" ng-model="Edit.ActorSex" ng-required="!Edit.ActorSex" />
                        </div>
                        <div class="col-md-2">
                            Female<input type="radio" name="gender" value="female" ng-model="Edit.ActorName" ng-required="!Edit.ActorSex" />
                        </div>
                        <div class="col-md-2">
                            Others<input type="radio" name="gender" value="others" ng-model="Edit.ActorSex" ng-required="!Edit.ActorSex" />
                        </div>
                        <span class="error" ng-show="(f1.gender.$dirty || submitted) && f1.gender.$error.required">Gender required!</span>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Date Of Birth</label>
                        <div class="col-sm-6">
                            <input type="date" name="date" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="Edit.ActorDOB" required autofocus />
                            <span class="error" ng-show="(f1.date.$dirty || submitted) && f1.date.$error.required">Date of Birth is required</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Bio</label>
                        <div class="col-sm-6">
                            <textarea rows="5" name="bio" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="Edit.ActorBio" required autofocus></textarea>
                            <span class="error" ng-show="(f1.bio.$dirty || submitted) && f1.bio.$error.required">Enter the bio</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <input type="submit" value="{{submitText}}" class="btn btn-primary">
                    <button type="button" class="btn btn-default" focus-element="autofocus" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

Movie_Management/Views/Movie/CreateMovie.cshtml
@{
    ViewBag.Title = "CreateMovie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Movie</h2>
&nbsp;
&nbsp;
<form class="form-horizontal" name="f1" novalidate ng-submit="saveMovie(movieName,yearOfRelease,plot,cast)" role="form" ng-controller="movieController">
    <div class="col-lg-12 col-sm-12 col-xs-12 alert alert-info" ng-show="bool">
        <strong>{{message}}</strong>
    </div>
    <div class="form-group">
        <label for="movieName" class="col-sm-3 control-label">Movie Name</label>
        <div class="col-sm-6">
            <input type="text" name="movieName" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="movieName" required />
            <span class="error" ng-show="(f1.movieName.$dirty || submitted) && f1.movieName.$error.required">Movie name is required!</span>
        </div>
        <div class="col-sm-3"></div>

    </div>
    <div class="form-group">
        <label for="yearOfRelease" class="col-sm-3 control-label">Year of Release</label>
        <div class="col-sm-6">
            <input type="text" name="yearOfRelease" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="yearOfRelease" required />
            <span class="error" ng-show="(f1.yearOfRelease.$dirty || submitted) && f1.yearOfRelease.$error.required">Year of release is required!</span>
        </div>
        <div class="col-sm-3"></div>
    </div>

    <div class="form-group">
        <label for="plot" class="col-sm-3 control-label">Plot</label>
        <div class="col-sm-6">
            <textarea rows="5" name="plot" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="plot" required></textarea>
            <span class="error" ng-show="(f1.plot.$dirty || submitted) && f1.plot.$error.required">Plot is required!</span>
        </div>
        <div class="col-sm-3"></div>
    </div>

    <div class="form-group">
        <div class="imageupload">
            <div class="file-tab panel-body">
                <label for="poster" class="col-sm-3 control-label">Poster</label>
                <div class="col-sm-6">
                    <label class="btn btn-default btn-file">
                        <span>Browse</span>
                        <input type="file" name="file" accept="image/*" onchange="angular.element(this).scope().selectFileforUpload(this.files)" required>
                    </label>
                    <button type="button" class="btn btn-default">Remove</button>
                    <span class="error" ng-show="(f1.file.$dirty || submitted) && f1.file.$error.required">Poster is required!</span>
                    <span class="error">{{FileInvalidMessage}}</span>
                </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>

    <div class='form-group '>
        <label for="Cast" class="col-sm-3 control-label">Cast</label>
        <div class="col-sm-3">
            <div class="dropdown cq-dropdown" data-name='statuses'>
                <button class="btn btn-info btn-sm dropdown-toggle " type="button" id="btndropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Select Actors
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="btndropdown">
                    <li ng-repeat="a in Actors">
                        <label class="radio-btn">
                            <input type="checkbox" name="cast" ng-model="cast" ng-change="change(a, cast)" value="{{a.ActorId}}" required />
                            {{a.ActorName}}
                        </label>
                    </li>
                    <li class='text-center'>
                        <button type='button' class='btn btn-sm btn-danger clear close-dropdown' value='Clear'>Clear</button>
                        <button type='button' class='btn btn-sm btn-success save' value='Save'>Save</button>
                    </li>
                </ul>
            </div>
            <span class="error" ng-show="(f1.cast.$dirty || submitted) && f1.cast.$error.required">Select Actor</span>
        </div>
        <div class="col-sm-1">
            <button type="button" class="btn btn-success" data-toggle="modal" focus-element="autofocus" data-target=".bs-example-modal-lg">
                <i class="fa fa-plus" style="margin-right:10px;"></i>
                Add Actor
            </button>
        </div>
    </div>



    <input type="submit" id="save" value="Save" class="btn btn-primary col-sm-offset-3" />
    <input type="reset" id="Reset" value="Reset" class="btn btn-danger" ng-click="resetForm()" />
</form>


<div class="modal fade bs-example-modal-lg" focus-group focus-group-head="loop" ng-controller="movieController" focus-group-tail="loop" focus-stacktabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Add Actor</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" ng-controller="movieController" novalidate name="f1" ng-submit="saveActor(actorName,gender,dob,bio)">
                    <div class="col-lg-12 col-sm-12 col-xs-12 alert alert-info" ng-show="bool">
                        <strong>{{message}}</strong>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Actor Name</label>
                        <div class="col-sm-6">
                            <input type="text" name="actorName" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="actorName" required autofocus />
                            <span class="error" ng-show="(f1.actorName.$dirty || submitted) && f1.actorName.$error.required">Name is required!</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Gender</label>
                        <div class="col-md-2">
                            Male<input type="radio" name="gender" value="male" ng-model="gender" ng-required="!gender" />
                        </div>
                        <div class="col-md-2">
                            Female<input type="radio" name="gender" value="female" ng-model="gender" ng-required="!gender" />
                        </div>
                        <div class="col-md-2">
                            Others<input type="radio" name="gender" value="others" ng-model="gender" ng-required="!gender" />
                        </div>
                        <span class="error" ng-show="(f1.gender.$dirty || submitted) && f1.gender.$error.required">Gender required!</span>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Date Of Birth</label>
                        <div class="col-sm-6">
                            <input type="date" name="date" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="dob" required autofocus />
                            <span class="error" ng-show="(f1.date.$dirty || submitted) && f1.date.$error.required">Date of Birth is required</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label for="movieName" class="col-sm-3 control-label">Bio</label>
                        <div class="col-sm-6">
                            <textarea rows="5" name="bio" ng-class="submitted?'ng-dirty':''" class="form-control" ng-model="bio" required autofocus></textarea>
                            <span class="error" ng-show="(f1.bio.$dirty || submitted) && f1.bio.$error.required">Enter the bio</span>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <input type="submit" value="{{submitText}}" class="btn btn-primary">
                    <button type="button" class="btn btn-default" focus-element="autofocus" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

Movie_Management/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container-fluid" ng-controller="movieController">
    <h2>TOP 10 MOVIES</h2>
    <button class="btn btn-success" style="float:right; margin-bottom:15px;">
        <i class="fa fa-plus" style="padding-right:5px;"></i>@Html.ActionLink("Movie", "CreateMovie", "Movie", new { area = " "}, new { @style = "color:black;" })
    </button>
    <table class="table table-responsive table-bordered">
        <thead>
            <tr>
                <th class="col-lg-3">Poster</th>
                <th class="col-lg-2">Movie Name</th>
                <th class="col-lg-1">Year Of Release</th>
                <th class="col-lg-3">Plot</th>
                <th class="col-lg-2">Cast</th>
                <th class="col-lg-1">Edit</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="a in movies | filter:serachText">
                <td><img ng-src="~/UploadedImages/{{a.ImagePath}}" /></td>
                <td>{{a.ShowName}}</td>
                <td>{{a.ShowYearOfRelaease}}</td>
                <td>{{a.ShowPlot}}</td>
                <td>{{a.Cast}}</td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", "Movie", new { area = " " }, new { ng_click = "editMovie(a.ShowId)" })*@
                                        <a><i class="fa fa-pencil" style="font-size:large;" ng-click="editMovie(a.ShowId)"></i></a>
                                    </td>
                    </tr>
                </tbody>
            </table>
            <div style="text-align:center;">
                <strong>{{message}}</strong>
            </div>
        </div>

Movie_Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="movieApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movie Management</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/font-awesome.css"/>
    <link rel="stylesheet" href="~/Content/bootstrap-imageupload.min.css"/>
    <link rel="stylesheet" href="~/Content/dropdownCheckboxes.min.css" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-controller="movieController">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                @Html.ActionLink("Movie Management", "Index", "Home", new { @class = "navbar-brand" })
            </div>
            <ul class="nav navbar-nav">
                <li class="active">@Html.ActionLink("Movie", "Index", "Movie", new {  }, new { @style = "margin-left:100px;" })</li>
                <li>@Html.ActionLink("Celebrities", "Index", "Actor", new { }, new { @style = "margin-left:100px;" })</li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="input-group">
                    <input type="text" class="form-control" ng-model="serachText" placeholder="Search" name="search">
                    <div class="input-group-btn">
                        @*<button class="btn btn-default"  type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>*@
                    </div>
                </div>
            </form>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="container-fluid bg-4 text-center">
            <p>&copy; @DateTime.Now.Year - Movie Management</p>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/Service/Module.js"></script>
    <script src="~/Scripts/Service/AngularController.js"></script>
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/Service/FunctionService.js"></script>
    <script src="~/Scripts/bootstrap-imageupload.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/dropdownCheckboxes.min.js"></script>
    <script src="~/Scripts/angular-focusmanager.js"></script>

    <script>
        $(document).ready(function () {
            var $imageupload = $('.imageupload');
            $imageupload.imageupload({
                allowedFormats: ['jpg', 'jpeg', 'png', 'gif'],
                maxWidth: 250,
                maxHeight: 250,
                maxFileSizeKb: 2048
            });

            $('.cq-dropdown').dropdownCheckboxes();

            $("#Reset").on('click', function () {
                $('.imageupload').imageupload('reset');
                $('input[type=checkbox]').prop('checked', false);
                $('.cq-dropdown').dropdownCheckboxes('eval');
            })

            $("#save").on('click', function () {
                $('.imageupload').imageupload('reset');
                $('input[type=checkbox]').prop('checked', false);
                $('.cq-dropdown').dropdownCheckboxes('eval');
            })
        });
    </script>
</body>
</html>